"""Constants for the Smart Video Hub integration."""

from datetime import timedelta

from homeassistant.const import CONF_HOST, CONF_PORT

DOMAIN = "smartvideohub"

# Configuration
CONF_HIDE_DEFAULT_INPUTS = "hide_default_inputs"

# Defaults
DEFAULT_PORT = 9990
DEFAULT_NAME = "VideoHub"

# Reconnect settings
RECONNECT_DELAY = 30
KEEPALIVE_INTERVAL = 120

# Protocol block names (from the Blackmagic Videohub Ethernet Protocol v2.3)
BLOCK_PROTOCOL_PREAMBLE = "PROTOCOL PREAMBLE"
BLOCK_VIDEOHUB_DEVICE = "VIDEOHUB DEVICE"
BLOCK_INPUT_LABELS = "INPUT LABELS"
BLOCK_OUTPUT_LABELS = "OUTPUT LABELS"
BLOCK_MONITORING_OUTPUT_LABELS = "MONITORING OUTPUT LABELS"
BLOCK_SERIAL_PORT_LABELS = "SERIAL PORT LABELS"
BLOCK_VIDEO_OUTPUT_ROUTING = "VIDEO OUTPUT ROUTING"
BLOCK_VIDEO_MONITORING_OUTPUT_ROUTING = "VIDEO MONITORING OUTPUT ROUTING"
BLOCK_SERIAL_PORT_ROUTING = "SERIAL PORT ROUTING"
BLOCK_PROCESSING_UNIT_ROUTING = "PROCESSING UNIT ROUTING"
BLOCK_FRAME_LABELS = "FRAME LABELS"
BLOCK_FRAME_BUFFER_ROUTING = "FRAME BUFFER ROUTING"
BLOCK_VIDEO_OUTPUT_LOCKS = "VIDEO OUTPUT LOCKS"
BLOCK_MONITORING_OUTPUT_LOCKS = "MONITORING OUTPUT LOCKS"
BLOCK_SERIAL_PORT_LOCKS = "SERIAL PORT LOCKS"
BLOCK_PROCESSING_UNIT_LOCKS = "PROCESSING UNIT LOCKS"
BLOCK_FRAME_BUFFER_LOCKS = "FRAME BUFFER LOCKS"
BLOCK_SERIAL_PORT_DIRECTIONS = "SERIAL PORT DIRECTIONS"
BLOCK_VIDEO_INPUT_STATUS = "VIDEO INPUT STATUS"
BLOCK_VIDEO_OUTPUT_STATUS = "VIDEO OUTPUT STATUS"
BLOCK_SERIAL_PORT_STATUS = "SERIAL PORT STATUS"
BLOCK_VIDEO_OUTPUT = "VIDEO OUTPUT"
BLOCK_STREAM_SETTINGS = "STREAM SETTINGS"
BLOCK_STREAM_STATE = "STREAM STATE"
BLOCK_IDENTITY = "IDENTITY"
BLOCK_TERANEX_MINI_DEVICE = "TERANEX MINI DEVICE"

# Lock states
LOCK_UNLOCKED = "U"
LOCK_OWNED = "O"
LOCK_LOCKED = "L"
LOCK_FORCE_UNLOCK = "F"

# Device models
MODEL_VIDEOHUB = "VideoHub"
MODEL_STREAMING = "Streaming"
MODEL_TERANEX = "TERANEX"

# Platforms
PLATFORMS = [
    "media_player",
    "select",
    "text",
    "button",
    "switch",
    "lock",
    "sensor",
]

# Service names
SERVICE_ROUTE_OUTPUT = "route_output"
SERVICE_ROUTE_ALL_OUTPUTS = "route_all_outputs"
SERVICE_SWAP_OUTPUTS = "swap_outputs"
SERVICE_ROUTE_BY_NAME = "route_by_name"

# Serial port directions
SERIAL_DIR_CONTROL = "control"
SERIAL_DIR_SLAVE = "slave"
SERIAL_DIR_AUTO = "auto"